config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { registrations: 'registrations' }

  resources :users
  resources :payments

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'


  root 'static_pages#index'

end

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="wrapper-footer">
    This site was built by Agustin Chavez
  </div>
</div>

app/views/shared/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    $<%= f.text_field :price %>
  </div>
  <div class="actions">
    <button type="submit" class="btn btn-default"><%= f.submit %></button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <li class="navbar-brand"><%= link_to 'Home', root_path %></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'About', static_pages_about_path %></li>
        <li><%= link_to 'Contact', static_pages_contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Inventory <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'New Product', new_product_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search" <%= form_tag("/products", method: "get") do %>
      <div class="form-group">
        <%= label_tag(:q, "Search for:") %>
      </div>
      <%= text_field_tag(:q) %>
        <button type="submit" class="btn btn-default"><%= submit_tag("Search") %></button>
      <% end %>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path)%>
              <% else %>
                <%= link_to('Login', new_user_session_path) %>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>

    <p>
      <div class="rating"></div>
    </p>

    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

<div class="product-reviews">
  <% @comments.each do |comment| %>
    <div class="row" id="individual-comments">
    <hr>
    <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
    <p><%= "Rating: #{comment.rating}/5" %></p>
    <div class="rated" data-score="<%= comment.rating %>"></div>
      <p><%= comment.body %></p>
      <p>
        <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
        <% if signed_in? && current_user.admin? %>
          <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </p>
    </div>
  <% end %>
<%= will_paginate @comments %>
</div>

app/views/shared/_product.html.erb
<ul class="products-list">
  <li class="products-display">
    <p><%= product.name %></p>
    <li class="Responsive image"><%= image_tag(product.image_url, :style => 'height: 100%; width: 100%;') %></li>
    <ul class="products-description">
      <li><p><strong class="products-labels">Description: </strong><br><%= truncate(product.description, length: 70) %></p></li>
      <li><p><strong class="products-labels">Color: </strong><%= product.colour %></p></li>
      <li><p><strong class="products-labels">Price: </strong>$<%= product.price %></p></li>
      <li>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to 'Show', product %>
          <%= link_to 'Edit', edit_product_path(product) %>
          <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% else %>
          <%= link_to 'Show', product %>
        <% end %>
      </li>
    </li>
</ul>

app/views/shared/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key]%>"
  data-amount="<%= @product.price %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-image=<%= @product.image_url %>>
</script>
<%= hidden_field_tag('product_id', @product.id) %>