config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :controllers => { registrations: 'registrations' }

  resources :users
  resources :payments

  resources :products do
    resources :comments
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'


  root 'static_pages#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  def total_sales
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
   protect_from_forgery
    skip_before_action :verify_authenticity_token, if: :json_request?
    respond_to :json, :html

    def index
      @orders = Order.all.to_json(:include => [{:product => {:only => :name}}, {:user => {:only => :email}}])
      respond_with @orders
    end

    def show
      @order = Order.find(params[:id]).to_json(:include => [{:product => {:only => :name}}, {:user => {:only => :email}}])
      respond_with @order
    end

    def new
    end

    def create
      @order = Order.create(order_params)
      respond_with @order
    end

    def destroy
      respond_with Order.destroy(params[:id])
    end

    protected

    def json_request?
      request.format.json?
    end

    private

    def order_params
      params.require(:order).permit(:product_id, :user_id, :total)
    end
end

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<!--Angular-->
<div ng-controller = "OrdersCtrl">

  <table class="table table-hover">
  <thead>
    <td>Order ID</td>
    <td>Product</td>
    <td>Total</td>

    <td></td>
  </thead>

  <tr>
  <form ng-submit="addOrder()">
    <td>
       <span ng-model="newOrder.id"> value="{{orders[orders.length - 1].id + 1 }}"  </span>
    </td>

    <td>
      <select ng-model="newOrder.product_id" class="form-control">
      <option ng-repeat="product in products" value="{{product.id}}">{{product.name}}</option>
      </select>
    </td>

    <td>
      <input type="number" step="0.01" class="form-control" ng-model="newOrder.total">
    </td>

    <td>
      <input type="submit" value="+" class="btn btn-success">
    </td>

    <td>
      <button ng-click="deleteOrder(order)" class="btn btn-danger btn-sm"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
    </td>

  </form>
  </tr>

  <tr ng-repeat="order in orders | orderBy:'-id':reverse">
    <td>
      {{order.id}}
    </td>
     <td>
      {{order.product.name}}
      <small ng-show="order.id"><br>-{{order.user.email}} </small>
    </td>
    <td>
      <strong>{{order.total | currency}}</strong>
    </td>
    <td>
      <!-- we will fill this later with content -->
    </td>
  </tr>

  </table>
</div>

app/views/orders/show.html.erb
<div class="show-orders">
  <p>
    <strong>User ID:</strong>
    {{order.user_id}}
  </p>

  <p>
    <strong>Product ID:</strong>
    {{order.product_id}}
  </p>

  <p>
    <strong>Total:</strong>
    {{order.total}}
  </p>
</div>

<%= link_to 'Back', orders_path %>